require("plugins.lsp")

require("plugins.alpha")
require("plugins.flash")
require("plugins.gitsigns")
require("plugins.hop")
require("plugins.indentblankline")
require("plugins.lsp-lines")
require("plugins.lualine")
require("plugins.mini-align")
require("plugins.mini-move")
require("plugins.nabla-nvim")
require("plugins.neorg")
-- require("plugins.neoscroll") -- fighting eof
require("plugins.nvim-activate")
require("plugins.nvim-cmp")
require("plugins.rainbowdelimiters")
require("plugins.scrollEOF")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.ultimate-autopair")
require("plugins.undotree")
require("plugins.venn")
