require("plugins.lsp")

require("plugins.alpha")
require("plugins.flash")
require("plugins.hop")
require("plugins.gitsigns")
require("plugins.indentblankline")
require("plugins.lsp-lines")
require("plugins.lualine")
require("plugins.mini-move")
require("plugins.nabla-nvim")
require("plugins.neorg")
require("plugins.nvim-cmp")
require("plugins.rainbowdelimiters")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.venn")
