vim.cmd.colorscheme("gruvbox")
--vim.cmd.colorscheme("solarized")

vim.cmd([[highlight Normal guibg=none]])
vim.cmd([[highlight NormalNC guibg=none]])
vim.cmd([[highlight EndOfBuffer guibg=none]])
vim.cmd([[highlight SignColumn guibg=none]])
vim.cmd([[highlight FloatBorder guibg=none]])
vim.cmd([[highlight NormalFloat guibg=none]])
vim.cmd([[highlight WinSeparator guibg=none]])
